# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLk7gweoXHi9QpQk360m6_CDD9qZDpSZ
"""

import cv2                                      # Import OpenCV for image processing
import numpy as np                              # Import NumPy for matrix operations
import matplotlib.pyplot as plt                 # Import Matplotlib for visualization

# Step 1: Create a synthetic grayscale image
img = np.zeros((200, 200), dtype=np.uint8)
cv2.circle(img, (100, 100), 60, 180, -1)        # Draw a gray circle

# Step 2: Simulate sensor noise (Gaussian noise)
noise = np.random.normal(0, 20, img.shape).astype(np.int16)
noisy_img = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)

# Step 3: Reduce noise using Gaussian Blur
denoised = cv2.GaussianBlur(noisy_img, (5, 5), 0)

# Step 4: Display the images
plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(132)
plt.imshow(noisy_img, cmap='gray')
plt.title("Noisy Image")
plt.axis("off")

plt.subplot(133)
plt.imshow(denoised, cmap='gray')
plt.title("Denoised Image")
plt.axis("off")

plt.show()