# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLk7gweoXHi9QpQk360m6_CDD9qZDpSZ
"""

import cv2                                      # Import OpenCV
import numpy as np                              # Import NumPy
import matplotlib.pyplot as plt                 # Import Matplotlib

# Step 1: Create a synthetic image with two objects
img = np.zeros((200, 200), dtype=np.uint8)
cv2.rectangle(img, (40, 50), (90, 150), 255, -1)      # Large object
cv2.circle(img, (150, 100), 20, 180, -1)              # Small object

# Step 2: Simulate low sampling (low resolution)
low_res = cv2.resize(img, (50, 50), interpolation=cv2.INTER_AREA)
low_res = cv2.resize(low_res, (200, 200), interpolation=cv2.INTER_NEAREST)

# Step 3: Simulate poor image formation (blur)
blurred = cv2.GaussianBlur(low_res, (7, 7), 2)

# Step 4: Display the images
plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(132)
plt.imshow(low_res, cmap='gray')
plt.title("Low Resolution Image")
plt.axis("off")

plt.subplot(133)
plt.imshow(blurred, cmap='gray')
plt.title("Blurred Image")
plt.axis("off")

plt.show()