# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLk7gweoXHi9QpQk360m6_CDD9qZDpSZ
"""

import cv2                                      # Import OpenCV for image processing
import numpy as np                              # Import NumPy for matrix operations
import matplotlib.pyplot as plt                 # Import Matplotlib for visualization

# Step 1: Create a synthetic grayscale gradient image
img = np.tile(np.arange(256, dtype=np.uint8), (100, 1))

# Step 2: Simulate low quantization (4-bit = 16 gray levels)
low_quantized = (img // 16) * 16

# Step 3: Display the original and quantized images
plt.figure(figsize=(8,4))

plt.subplot(121)
plt.imshow(img, cmap='gray')
plt.title("Original Grayscale Image")
plt.axis("off")

plt.subplot(122)
plt.imshow(low_quantized, cmap='gray')
plt.title("Low Quantized Image")
plt.axis("off")

plt.show()