# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLk7gweoXHi9QpQk360m6_CDD9qZDpSZ
"""

import cv2                                      # Import OpenCV
import numpy as np                              # Import NumPy
import matplotlib.pyplot as plt                 # Import Matplotlib

# Step 1: Create a synthetic face-like image
img = np.zeros((200, 200), dtype=np.uint8)

cv2.circle(img, (100, 100), 60, 255, -1)        # Face
cv2.circle(img, (80, 85), 6, 0, -1)             # Left eye
cv2.circle(img, (120, 85), 6, 0, -1)            # Right eye
cv2.ellipse(img, (100, 120), (20, 10), 0, 0, 180, 0, 2)  # Smile

# Step 2: Simulate image acquisition with Gaussian blur
captured = cv2.GaussianBlur(img, (5,5), 0)

# Step 3: Detect edges (feature extraction)
edges = cv2.Canny(captured, 50, 150)

# Step 4: Display images
plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(img, cmap='gray')
plt.title("Captured Face")
plt.axis("off")

plt.subplot(132)
plt.imshow(captured, cmap='gray')
plt.title("Preprocessed Image")
plt.axis("off")

plt.subplot(133)
plt.imshow(edges, cmap='gray')
plt.title("Extracted Features")
plt.axis("off")

plt.show()