# -*- coding: utf-8 -*-
"""CO1-AT1-Q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6GpbM4iXm2TbEoU9nokTVHuDZ3RY7pv
"""

import cv2                                      # Import OpenCV for image processing
import numpy as np                              # Import NumPy for matrix operations
import matplotlib.pyplot as plt                 # Import Matplotlib for displaying images

# Step 1: Create a synthetic image representing a real-world scene
img = np.zeros((200, 200), dtype=np.uint8)      # Create a black image
cv2.rectangle(img, (40, 40), (160, 160), 180, -1)  # Draw a gray square
cv2.circle(img, (100, 100), 40, 255, -1)        # Draw a white circle

# Step 2: Simulate low-light image acquisition
low_light = cv2.convertScaleAbs(img, alpha=0.25, beta=0)

# Step 3: Simulate sensor noise during image sensing
noise = np.random.normal(0, 15, low_light.shape).astype(np.int16)
noisy_image = np.clip(low_light.astype(np.int16) + noise, 0, 255).astype(np.uint8)

# Step 4: Enhance the captured image using Histogram Equalization
enhanced = cv2.equalizeHist(noisy_image)

# Step 5: Display all images
plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(low_light, cmap='gray')
plt.title("Low-Light Image")
plt.axis("off")

plt.subplot(132)
plt.imshow(noisy_image, cmap='gray')
plt.title("Captured Image with Noise")
plt.axis("off")

plt.subplot(133)
plt.imshow(enhanced, cmap='gray')
plt.title("Enhanced Image")
plt.axis("off")

plt.show()