# -*- coding: utf-8 -*-
"""CO1-AT1-Q03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpssYWJUcCnC4CX7tO9Dp47Ec-0nfq_A
"""

import cv2                                  # Import OpenCV
import numpy as np                          # Import NumPy
import matplotlib.pyplot as plt             # Import Matplotlib

# Step 1: Create a synthetic image with fine details
img = np.zeros((200, 200), dtype=np.uint8)

# Draw closely spaced white lines
for i in range(20, 180, 8):
    cv2.line(img, (i, 20), (i, 180), 255, 1)

# Step 2: Simulate aliasing by reducing sampling
low_res = cv2.resize(img, (50, 50), interpolation=cv2.INTER_NEAREST)

# Step 3: Apply Anti-Aliasing (Gaussian Blur)
blurred = cv2.GaussianBlur(low_res, (5,5), 0)

# Step 4: Restore image using Bicubic Interpolation
corrected = cv2.resize(blurred, (200, 200), interpolation=cv2.INTER_CUBIC)

# Step 5: Display results
plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(132)
plt.imshow(low_res, cmap='gray')
plt.title("Aliased Image")
plt.axis("off")

plt.subplot(133)
plt.imshow(corrected, cmap='gray')
plt.title("Corrected Image")
plt.axis("off")

plt.show()