# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLk7gweoXHi9QpQk360m6_CDD9qZDpSZ
"""

import cv2                                          # Import OpenCV for image processing
import numpy as np                                  # Import NumPy for matrix operations
import matplotlib.pyplot as plt                     # Import Matplotlib for visualization

# Step 1: Create a synthetic static background
background = np.zeros((200, 200), dtype=np.uint8)   # Create a blank black image

# Step 2: Create a surveillance frame with a moving object
frame = background.copy()
cv2.rectangle(frame, (70, 70), (120, 120), 255, -1) # Draw a white square representing a moving object

# Step 3: Detect the moving object using frame difference
motion = cv2.absdiff(background, frame)             # Compute absolute difference between frames

# Step 4: Convert the difference into a binary motion mask
_, motion_mask = cv2.threshold(motion, 50, 255, cv2.THRESH_BINARY)

# Step 5: Display the images
plt.figure(figsize=(9,3))

plt.subplot(131)
plt.imshow(background, cmap='gray')
plt.title("Background")
plt.axis("off")

plt.subplot(132)
plt.imshow(frame, cmap='gray')
plt.title("Surveillance Frame")
plt.axis("off")

plt.subplot(133)
plt.imshow(motion_mask, cmap='gray')
plt.title("Detected Motion")
plt.axis("off")

plt.show()