# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLk7gweoXHi9QpQk360m6_CDD9qZDpSZ
"""

import cv2                                  # Import OpenCV
import numpy as np                          # Import NumPy
import matplotlib.pyplot as plt             # Import Matplotlib

# Step 1: Create a synthetic medical-like grayscale image
img = np.zeros((256, 256), dtype=np.uint8)

cv2.circle(img, (128, 128), 70, 180, -1)     # Simulate organ
cv2.circle(img, (128, 128), 30, 230, -1)     # Simulate abnormal region

# Step 2: Simulate low pixel resolution
low_pixel = cv2.resize(img, (64, 64), interpolation=cv2.INTER_AREA)
low_pixel = cv2.resize(low_pixel, (256, 256), interpolation=cv2.INTER_NEAREST)

# Step 3: Simulate low intensity resolution (4-bit = 16 gray levels)
low_intensity = (img // 16) * 16

# Step 4: Display all images
plt.figure(figsize=(12,4))

plt.subplot(131)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(132)
plt.imshow(low_pixel, cmap='gray')
plt.title("Low Pixel Resolution")
plt.axis("off")

plt.subplot(133)
plt.imshow(low_intensity, cmap='gray')
plt.title("Low Intensity Resolution")
plt.axis("off")

plt.show()